steps:
- id: 'Install dependencies'
  name: 'gcr.io/cloud-builders/npm'
  args: [ 'install' ]
- id: 'postinstall'
  name: 'gcr.io/cloud-builders/npm'
  args: [ 'run', 'postinstall' ]
- id: 'Unit tests'
  name: 'gcr.io/cloud-builders/npm'
  args: [ 'test' ]
- id: 'Run build.prod'
  name: 'gcr.io/cloud-builders/npm'
  args: [ 'run', 'build.prod' ]
- id: 'Firebase deploy to production'
  name: 'gcr.io/$PROJECT_ID/firebase-builder'
  args: [ 'deploy', '-P', 'js-demo-fe-prod', '--token', '1/t_PDRgQ3QSsOR3v0z-HwMGtmZu_Bp8ttGrJCsgFrs8PtnSd0B0d_cXhXNbPabhRH']
- id: 'Create docs'
  name: 'gcr.io/cloud-builders/npm'
  args: [ 'run', 'compodoc' ]
- id: 'Push docs to GCS'
  name: 'gcr.io/cloud-builders/gsutil'
  args: [ 'cp', '-r', 'documentation', 'gs://js-demo-fe-docs' ]  