steps:

# Submit PR
- name: 'gcr.io/cloud-builders/wget'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cat <<EOF > /.config/hub
      github.com:
      - user: christophersanson
        oauth_token: test
        protocol: https
      EOF
  ]
